version: "3.8"

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  maps:
    image: maps:latest
    ports:
      - "8080:8080"
      - "1883:1883"
    environment:
      - MAPS_HOME=/maps-3.3.7-SNAPSHOT
      - MAPS_DATA=/maps/data
      - ConsulHost=consul
      - ConsulPort=8500
      - ForceConsul=true
    volumes:
      - maps-data:/maps/data
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  weather-worker:
    build: ./weather-worker
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - MAPS_URL=http://maps:8080/v1/messages/publish
    depends_on:
      maps:
        condition: service_healthy
    networks:
      - app-network

  mqtt-bridge:
    build: ./mqtt-bridge
    depends_on:
      maps:
        condition: service_healthy
    networks:
      - app-network

  webhook-mock:
    build: ./webhook-mock
    ports:
      - "9999:9999"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  maps-data:
    driver: local