services:
  maps:
    image: mapsmessaging/server_daemon_arm_3.3.7-snapshot
    container_name: maps
    ports:
      - "8080:8080"
      - "4222:4222"
      - "1883:1883"
    environment:
      - MAPS_AUTH_TOKEN=supersecrettoken
    restart: unless-stopped

  weather-worker:
    build:
      context: ./weather-worker
    container_name: weather-worker
    depends_on:
      - maps
    environment:
      - MAPS_URL=http://localhost:8080
      - MAPS_TOKEN=supersecrettoken
      - OPENWEATHERMAP_API_KEY=your_openweathermap_api_key_here
    volumes:
      - ./weather-worker:/app
    restart: unless-stopped

  mqtt-rest-bridge:
    build:
      context: ./mqtt-bridge
    container_name: mqtt-bridge
    depends_on:
      - maps
    environment:
      - MAPS_TOKEN=supersecrettoken
      - WEBHOOK_URL=http://webhook-mock:5001/webhook
    restart: unless-stopped

  webhook-mock:
    build:
      context: ./webhook-mock
    container_name: webhook-mock
    ports:
      - "5001:5001"
    restart: unless-stopped