name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Weather Worker
        run: docker build -f weather-worker/Dockerfile weather-worker

      - name: Build MQTT Bridge
        run: docker build -f mqtt-bridge/Dockerfile mqtt-bridge

      - name: Build Webhook Mock
        run: docker build -f webhook-mock/Dockerfile webhook-mock